apiVersion: apps/v1
kind: Deployment
metadata:
  name: apiteste-deployment
  labels:
    app: api
spec:
  # Garante que sempre haverá 1 Pod rodando
  replicas: 2
  selector:
    matchLabels:
      app: apiteste
  template:
    metadata:
      labels:
        app: apiteste
    spec:
      containers:
        - name: apiteste
          # Sua imagem Docker
          image: andersongomesc/apiteste:{{tag}}

          # Padrão: usa a porta 8080 para o Jenkins
          ports:
            - containerPort: 8080
              name: http-port

            # Padrão: usa a porta 50000 para comunicação JNLP (Agentes)
            - containerPort: 50000
              name: jnlp-port